language: java
sudo: required
os:
  - linux
dist: trusty
script: 
- mvn clean test -P chrome_opensource -e
- mvn clean test -P firefox_opensource -e
- mvn clean test -P ie_opensource -e
- mvn clean test -P edge_opensource -e
- mvn clean test -P safari_opensource -e